apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secret
  namespace: togglemaster
type: Opaque
stringData:

  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"

  MASTER_KEY: "admin-secreto-123"
  SERVICE_API_KEY: "SUA_CHAVE_DE_SERVICO"

  POSTGRES_PASSWORD_AUTH: "auth_password"
  POSTGRES_PASSWORD_FLAG: "flag_password"
  POSTGRES_PASSWORD_TARGET: "target_password"