apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
  namespace: togglemaster
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::973397181776:role/evaluation-service-role
