apiVersion: v1
kind: Secret
metadata:
  name: target-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:ChangeMe123@tm-db.cgx4okc4isem.us-east-1.rds.amazonaws.com:5432/target_db"