apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: togglemaster
type: Opaque
stringData:
  MASTER_KEY: admin-secreto-123
  SERVICE_API_KEY: "SUA_CHAVE_DE_SERVICO"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/973397181776/evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
