apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: togglemaster/analytics-service:latest
          ports:
            - containerPort: 8005
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: ANALYTICS_PORT
          envFrom:
            - configMapRef:
                name: togglemaster-config
            - secretRef:
                name: togglemaster-secret