apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      serviceAccountName: analytics-service
      containers:
        - name: analytics-service
          image: 973397181776.dkr.ecr.us-east-1.amazonaws.com/analytics-service:latest
          ports:
            - containerPort: 8005
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 600m
              memory: 1Gi
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: ANALYTICS_PORT
          envFrom:
            - configMapRef:
                name: togglemaster-config
            - secretRef:
                name: analytics-secret
