apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service-sqs-scaler
  namespace: togglemaster
spec:
  scaleTargetRef:
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: "https://sqs.us-east-1.amazonaws.com/973397181776/evaluation-events"
      queueLength: "5"
      awsRegion: "us-east-1"
      identityOwner: "workload"
    authenticationRef:
      name: analytics-sqs-auth
  pollingInterval: 10
  cooldownPeriod: 300
